### ISSUE TITLE
REPORTE DE PRACTICA (ENTREVISTA)

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-8#1]
[REPORTE DE PRACTICA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-8/files/9954209/REPORTE.DE.PRACTICA.pdf)

**Comment by Jaczibeth** [comment]
del 20% obtuvieron un 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
